Feature/add conversion tests
ONLYOFFICE-QA/x2ttester_wrapper pull request #9
Opened 2022-11-21 10:20 UTC by l8556

2022-11-21 12:59 UTC, ShockwaveNN requested changes

2022-11-21 12:59 UTC, ShockwaveNN commented on Rakefile
> +    message = 'Input Error. Please, enter the correct parameters, Example: rake convert[direction,cores]'
Maybe `raise`, not just a message but raise an exception

2022-11-21 12:59 UTC, ShockwaveNN commented on config/static_data.rb
> +  PROJECT_DIR = Dir.pwd
Maybe implement those as methods, not constants

I think this allow some runtime modification in future if neede, but for contstants it's not so accurate

2022-11-21 12:59 UTC, ShockwaveNN commented on framework/actions/core_actions.rb
> +    @version = "v#{StaticData::CONFIG.fetch('version')}".sub(/.*\K\..*/, '')
I would extract this to method and maybe add unit test

If you see an regexp better add unit test just in case )

2022-11-21 12:59 UTC, ShockwaveNN commented on framework/actions/core_actions.rb
> +    return unless StaticData::HOST.include?('linux') || StaticData::HOST.include?('mac')
Maybe use not constants, but `@os`

2022-11-21 12:59 UTC, ShockwaveNN commented on framework/actions/host_actions.rb
> +      ['linux', Gem::Platform.local.cpu.sub('86_', ''), 'x2t', 'x2ttester', 'standardtester']
Maybe return it as hash, so it's better structured and not depends of order

2022-11-21 12:59 UTC, ShockwaveNN commented on framework/actions/core_actions.rb
> +      p "Core not found, check version and branch settings are correct\nURL:#{@url}\nCurl response:#{core_status}"
Once again - maybe rais an exception

2022-11-21 12:59 UTC, ShockwaveNN commented on framework/actions/xml_actions.rb
> +  def self.generate_parameters(cores, direction = 'all')
Maybe add unit test for that method, it's rather complicated but generate simple xml which we can compare to

2022-11-22 09:18 UTC, ShockwaveNN submitted a review, later dismissed

2023-03-10 14:00 UTC, askonev approved these changes

2023-03-10 14:14 UTC, merged